# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Normalized RMSE
#'
#' @param output Data set of interest with columns as variables.
#' @param target Reference data set with same dimension as \code{output}.
#'
#' @return NRMSE of \code{output} relative to \code{target}.
NRMSE <- function(output, target) {
    .Call(`_conceptorCP_NRMSE`, output, target)
}

#' Run a recurrent neural network
#'
#' @param input A scaled T\code{x}d data set with variables as columns.
#' @param W RNN matrices output from \code{initRNN} function.
#' @param RSInitial Initial reservoir state.
#' @param bscale Scale of RNN bias matrix.
#' @param iscale Scale of RNN input matrix.
#'
#' @return RNN reservoir states for all T points.
runRNN <- function(input, W, RSInitial, bscale, iscale) {
    .Call(`_conceptorCP_runRNN`, input, W, RSInitial, bscale, iscale)
}

#' Compute conceptor matrices
#'
#' @param RS Reservoir states for conceptor computation.
#' @param aperture Aperture parameter.
#'
#' @return Conceptor matrix(ces).
conceptorCalc <- function(RS, aperture) {
    .Call(`_conceptorCP_conceptorCalc`, RS, aperture)
}

#' Run a recurrent neural network with conceptor matrix
#'
#' @param input A scaled T\code{x}d data set with variables as columns.
#' @param W RNN matrices output from \code{initRNN} function.
#' @param C Conceptor matrix(ces).
#' @param RSInitial Initial reservoir state.
#' @param washoutL Number of time points used for reservoir washout.
#' @param bscale Scale of RNN bias matrix.
#' @param iscale Scale of RNN input matrix.
#'
#' @return RNN reservoir states (controlled by a conceptor) for all T points.
runCRNN <- function(input, W, C, RSInitial, washoutL, bscale, iscale) {
    .Call(`_conceptorCP_runCRNN`, input, W, C, RSInitial, washoutL, bscale, iscale)
}

#' Compute RNN output matrix
#'
#' @param input A scaled T\code{x}d data set with variables as columns.
#' @param ResStates Reservoir states from \code{runCRNN}.
#' @param regular Regularization parameter for ridge regression.
#'
#' @return RNN output matrix(ces).
WoutCalc <- function(input, ResStates, regular) {
    .Call(`_conceptorCP_WoutCalc`, input, ResStates, regular)
}

#' Compute RNN output
#'
#' @param Wout RNN output matrix from \code{WoutCalc}
#' @param CResStates Reservoir states from \code{runCRNN}.
#'
#' @return Output from RNN.
outputCalc <- function(Wout, CResStates) {
    .Call(`_conceptorCP_outputCalc`, Wout, CResStates)
}

#' Fit RNN parameters to data
#'
#' @param input A scaled T\code{x}d data set with variables as columns.
#' @param W RNN matrices output from \code{initRNN} function.
#' @param RSInitial Initial reservoir state.
#' @param washoutL Number of time points used for reservoir washout.
#' @param trainL Number of time points used for conceptor training.
#' @param bscales Scalings for RNN bias matrix.
#' @param iscales Scalings for RNN input matrix.
#'
#' @return RNN parameters for best fit to data.
RNNParamFit <- function(input, W, RSInitial, washoutL, trainL, bscales, iscales) {
    .Call(`_conceptorCP_RNNParamFit`, input, W, RSInitial, washoutL, trainL, bscales, iscales)
}

#' Compute cosine similarity between reservoir and conceptor
#'
#' @param RS Reservoir states from \code{runCRNN} before conceptor multiplication.
#' @param CRS Reservoir states from \code{runCRNN} after conceptor multiplication.
#'
#' @return Cosine similarities between reservoir and conceptor space at each time point.
angleCalc <- function(RS, CRS) {
    .Call(`_conceptorCP_angleCalc`, RS, CRS)
}

#' Compute Kolmogorov-Smirnov test statistic
#'
#' @param angles Cosine similarities from \code{angleCalc}.
#'
#' @return Kolmogorov-Smirnov like statistic at each time point.
KSstatCalc <- function(angles) {
    .Call(`_conceptorCP_KSstatCalc`, angles)
}

#' Run a RNN with conceptor matrix on bootstrapped data
#'
#' @param bootinput A scaled T\code{x}d bootstrap data set with variables as columns.
#' @param W RNN matrices output from \code{initRNN} function.
#' @param C Conceptor matrix(ces).
#' @param RSInitial Initial reservoir state.
#' @param washoutL Number of time points used for reservoir washout.
#' @param trainL Number of time points used for conceptor training.
#' @param bscale Scale of RNN bias matrix.
#' @param iscale Scale of RNN input matrix.
#'
#' @return RNN reservoir states (controlled by a conceptor) for bootstrapped data.
CRNNBootstrap <- function(bootinput, W, C, RSInitial, washoutL, trainL, bscale, iscale) {
    .Call(`_conceptorCP_CRNNBootstrap`, bootinput, W, C, RSInitial, washoutL, trainL, bscale, iscale)
}

rcpparma_hello_world <- function() {
    .Call(`_conceptorCP_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_conceptorCP_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_conceptorCP_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_conceptorCP_rcpparma_bothproducts`, x)
}

