# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Normalized RMSE
#'
#' @param output T\code{x}d series of interest
#' @param target T\code{x}d reference series
#'
#' @return average NRMSE of columns
NRMSE <- function(output, target) {
    .Call(`_conceptorCP_NRMSE`, output, target)
}

#' Propagate RNN
#'
#' @param input T\code{x}d data
#' @param W cube of RNN matrices
#' @param RSInitial initial reservoir state
#' @param bscale bias matrix scaling
#' @param iscale input matrix scaling
#'
#' @return RNN reservoir states
runRNN <- function(input, W, RSInitial, bscale, iscale) {
    .Call(`_conceptorCP_runRNN`, input, W, RSInitial, bscale, iscale)
}

#' Compute conceptors
#'
#' @param RS reservoir states
#' @param aperture aperture value
#'
#' @return conceptor matrices
conceptorCalc <- function(RS, aperture) {
    .Call(`_conceptorCP_conceptorCalc`, RS, aperture)
}

#' Propagate RNN with conceptors
#'
#' @param input T\code{x}d data
#' @param W cube of RNN matrices
#' @param C cube of conceptor matrices
#' @param RSInitial initial reservoir state
#' @param washoutL length of reservoir washout
#' @param bscale bias matrix scaling
#' @param iscale input matrix scaling
#'
#' @return conceptor multiplied reservoir states
runCRNN <- function(input, W, C, RSInitial, washoutL, bscale, iscale) {
    .Call(`_conceptorCP_runCRNN`, input, W, C, RSInitial, washoutL, bscale, iscale)
}

#' Title Compute RNN output matrix
#'
#' @param input T\code{x}d data
#' @param ResStates reservoir states from RNN
#' @param regular Ridge regression regularization parameter
#'
#' @return Wout output matrix
WoutCalc <- function(input, ResStates, regular) {
    .Call(`_conceptorCP_WoutCalc`, input, ResStates, regular)
}

#' Compute RNN output
#'
#' @param Wout RNN output matrix from WoutCalc
#' @param CResStates conceptor multiplied reservoir states
#'
#' @return CRNN output
outputCalc <- function(Wout, CResStates) {
    .Call(`_conceptorCP_outputCalc`, Wout, CResStates)
}

#' Fit RNN to data
#'
#' @param input T\code{d} data
#' @param W cube of RNN matrices
#' @param RSInitial initial resercoir state
#' @param washoutL length of reservoir washout
#' @param trainL length of conceptor training
#' @param bscales bias matrix scalings
#' @param iscales input matrix scalings
#'
#' @return RNN parameters
RNNParamFit <- function(input, W, RSInitial, washoutL, trainL, bscales, iscales) {
    .Call(`_conceptorCP_RNNParamFit`, input, W, RSInitial, washoutL, trainL, bscales, iscales)
}

#' Compute cosine similarities
#'
#' @param RS RNN reservoir states
#' @param CRS conceptor multiplied reservoir states
#'
#' @return cosine similarity sequence
angleCalc <- function(RS, CRS) {
    .Call(`_conceptorCP_angleCalc`, RS, CRS)
}

#' Compute CUSUM-like statistic
#'
#' @param angles cosine similarity sequence
#' @param kappa small constant > 0
#'
#' @return modified Kolmogorov-Smirnov test statistic
KSstatCalc <- function(angles, kappa) {
    .Call(`_conceptorCP_KSstatCalc`, angles, kappa)
}

#' Compute MBB null distribution
#'
#' @param bootinput bootstrapped data input
#' @param W cube of RNN matrices
#' @param C cube of conceptor matrices
#' @param RSInitial initial reservoir state
#' @param washoutL length of reservoir washout
#' @param trainL length of conceptor training
#' @param bscale bias matrix scaling
#' @param iscale input matrix scaling
#' @param kappa
#'
#' @return bootstrap null distribution of CUSUM-like statistics
CRNNBootstrap <- function(bootinput, W, C, RSInitial, washoutL, trainL, bscale, iscale, kappa) {
    .Call(`_conceptorCP_CRNNBootstrap`, bootinput, W, C, RSInitial, washoutL, trainL, bscale, iscale, kappa)
}

rcpparma_hello_world <- function() {
    .Call(`_conceptorCP_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_conceptorCP_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_conceptorCP_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_conceptorCP_rcpparma_bothproducts`, x)
}

