# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate NRMSE
#'
#' @param output observed data
#' @param target reference data
#'
#' @return NRMSE of observed data to target data
NRMSE <- function(output, target) {
    .Call(`_conceptorCP_NRMSE`, output, target)
}

#' Run a RNN with specifications
#'
#' @param input data
#' @param W RNN matrices
#' @param RSInitial initial reservoir state
#' @param bscale bias matrix scaling
#' @param iscale input matrix scaling
#'
#' @return RNN reservoir states
runRNN <- function(input, W, RSInitial, bscale, iscale) {
    .Call(`_conceptorCP_runRNN`, input, W, RSInitial, bscale, iscale)
}

#' Compute conceptor matrices
#'
#' @param RS reservoir states
#' @param aperture aperture value
#'
#' @return conceptor matrices
conceptorCalc <- function(RS, aperture) {
    .Call(`_conceptorCP_conceptorCalc`, RS, aperture)
}

#' Run a RNN with conceptor matrix
#'
#' @param input data
#' @param W RNN matrices
#' @param C conceptor matrices
#' @param RSInitial initial reservoir state
#' @param washoutL length of washout
#' @param bscale bias matrix scaling
#' @param iscale input matrix scaling
#'
#' @return RNN reservoir states with conceptor control
runCRNN <- function(input, W, C, RSInitial, washoutL, bscale, iscale) {
    .Call(`_conceptorCP_runCRNN`, input, W, C, RSInitial, washoutL, bscale, iscale)
}

#' Compute output matrix
#'
#' @param input data
#' @param ResStates reservoir states
#' @param regular regularization parameter
#'
#' @return Wout matrix from ridge regression
WoutCalc <- function(input, ResStates, regular) {
    .Call(`_conceptorCP_WoutCalc`, input, ResStates, regular)
}

#' Compute RNN output
#'
#' @param Wout output matrix from WoutCalc
#' @param CResStates reservoir states with conceptor control
#'
#' @return CRNN output
outputCalc <- function(Wout, CResStates) {
    .Call(`_conceptorCP_outputCalc`, Wout, CResStates)
}

#' Fit RNN parameters
#'
#' @param input data
#' @param W RNN matrices
#' @param RSInitial initial reservoir state
#' @param washoutL length of washout data
#' @param trainL length of trainind data
#' @param bscales bias matrix scaling vector
#' @param iscales input matrix scaling vector
#'
#' @return optimal RNN parameters
RNNParamFit <- function(input, W, RSInitial, washoutL, trainL, bscales, iscales) {
    .Call(`_conceptorCP_RNNParamFit`, input, W, RSInitial, washoutL, trainL, bscales, iscales)
}

#' Compute angles between reservoir and conceptor space
#'
#' @param RS reservoir states
#' @param CRS conceptor states
#'
#' @return conputed angles
angleCalc <- function(RS, CRS) {
    .Call(`_conceptorCP_angleCalc`, RS, CRS)
}

#' Compute CUSUM like statistic
#'
#' @param angles angles between reservoir and conceptor
#' @param kappa small constant > 0
#'
#' @return CUSUM like statistic
KSstatCalc <- function(angles, kappa) {
    .Call(`_conceptorCP_KSstatCalc`, angles, kappa)
}

#' Bootstrap for CRNN
#'
#' @param bootinput bootstrapped data
#' @param W RNN matrices
#' @param C conceptor matrices
#' @param RSInitial initial reservoir state
#' @param washoutL length of washout data
#' @param trainL length of training data
#' @param bscale bias matrix scaling
#' @param iscale input matrix scaling
#' @param kappa small constant > 0
#'
#' @return bootstraped statistics
CRNNBootstrap <- function(bootinput, W, C, RSInitial, washoutL, trainL, bscale, iscale, kappa) {
    .Call(`_conceptorCP_CRNNBootstrap`, bootinput, W, C, RSInitial, washoutL, trainL, bscale, iscale, kappa)
}

rcpparma_hello_world <- function() {
    .Call(`_conceptorCP_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_conceptorCP_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_conceptorCP_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_conceptorCP_rcpparma_bothproducts`, x)
}

